@id=e9328014-2a4a-40f4-9ec0-2c105115d9c6
PUT http://localhost:5036/api/breakfasts/{{id}}
Content-Type: application/json

{
    "name": "Burger",
    "description": "Meat forever! Join us for a delicious breakfast..",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Hamburger",
        "Bacon",
        "Fried Chicken",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}